# Generated by Django 4.2.5 on 2023-10-02 02:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('accessible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('building_name', models.CharField(max_length=64)),
                ('floor_index', models.IntegerField()),
                ('path', models.TextField(blank=True, null=True)),
                ('floor_entrance', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'floor',
                'unique_together': {('building_name', 'floor_index')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('room_number', models.CharField(max_length=64)),
                ('room_type', models.TextField(blank=True, null=True)),
                ('door_coordinate', models.TextField()),
                ('accessible_door', models.BooleanField(blank=True, null=True)),
                ('inside_accessibility', models.BooleanField(blank=True, null=True)),
                ('room_name', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('min_stairs_needed', models.IntegerField(blank=True, db_comment='When accessibility is false', null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routedb.building')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routedb.floor')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='EntranceRoomDoor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('entrance_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('room_door_accessible_building_door', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'entrance_room_door',
                'unique_together': {('entrance_id', 'room_door_accessible_building_door')},
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('building_name', models.CharField(max_length=64)),
                ('accessible', models.BooleanField(blank=True, null=True)),
                ('wheelchair_button', models.BooleanField(blank=True, null=True)),
                ('coordinate', models.TextField(blank=True, null=True)),
                ('interior_coodinate', models.TextField(blank=True, null=True)),
                ('direction', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrance',
                'db_table_comment': 'We could find a better way to identify the doors later (building door)',
                'unique_together': {('id', 'building_name')},
            },
        ),
    ]
