# Generated by Django 4.2.5 on 2023-10-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('accessible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('building_name', models.CharField(max_length=64)),
                ('accessible', models.BooleanField(blank=True, null=True)),
                ('wheelchair_button', models.BooleanField(blank=True, null=True)),
                ('coordinate', models.TextField(blank=True, null=True)),
                ('interior_coodinate', models.TextField(blank=True, null=True)),
                ('direction', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrance',
                'db_table_comment': 'We could find a better way to identify the doors later (building door)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntranceRoomDoor',
            fields=[
                ('entrance_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('room_door_accessible_building_door', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'entrance_room_door',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('building_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('floor_index', models.IntegerField()),
                ('path', models.TextField(blank=True, null=True)),
                ('floor_entrance', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'floor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('floor', models.IntegerField()),
                ('room_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('room_type', models.TextField(blank=True, null=True)),
                ('door_coordinate', models.TextField()),
                ('accessible_door', models.BooleanField(blank=True, null=True)),
                ('inside_accessibility', models.BooleanField(blank=True, null=True)),
                ('room_name', models.TextField(blank=True, null=True)),
                ('building_name', models.CharField(max_length=64)),
                ('tags', models.TextField(blank=True, null=True)),
                ('min_stairs_needed', models.IntegerField(blank=True, db_comment='When accessibility is false', null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
    ]
